# Welcome to Jekyll!

# Website settings
title: "Gaurav"
description: "Gaurav's blog"
keywords: "Gaurav's blog"
baseurl: "/"
url: "http://gauravnagar.me"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Gaurav'
  first_name: 'Gaurav'
  last_name: 'Nagar'
  email: 'XXXX.com'
  facebook_username: 'gauravnagar19'
  github_username: 'gauravnagar19'
  linkedin_username: 'gaurav-nagar'
  avatar: 'static/img/landing/gauravnagarphoto.jpg'
  desc: 'I am Oracle Certified PL/SQL Developer with 3.8 years of Oracle Database/ERP experience at Capgemini India Pvt. Ltd. My primary task involved the development of BI reports and data migration (ETL) scripts using SQL and PL/SQL for the clients. I have also worked on customization of Oracle Web Pages using Java.'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
